version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: vocality-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vocality
      MYSQL_USER: acreus
      MYSQL_PASSWORD: vocreus
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: vocality-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_PORT: 3306
    ports:
      - "8080:80"

volumes:
  mysql_data: